### ISSUE TITLE
Is detect properties can be used as arguments?

### ISSUE THREAD

**Issue by vcmgc27** [blackducksoftware/bd-splitter#1]
Hello,

Is it possible to configure bd-splitter.py with detect properties like enabling copyright and license search, also snippet matches.

So, the scan splits runs the above properties as well.

Let me know.

Thanks

**Comment by gsnyder2007** [comment]
I've enhanced the code to allow the user to supply a file with the additional detect options (one per line). See the sample properties file also included and which I used to test the feature.
